### ISSUE TITLE
Frame problem

### ISSUE THREAD

**Issue by brunocalado** [jcolson/token_frames#5]
![image](https://user-images.githubusercontent.com/4999783/151001601-9dca6f72-c30a-4737-acb2-892399647fd8.png)

**Comment by jcolson** [comment]
for this one, the best bet would most likely be to use the _MASK.png layer for the mask .... and then size it to encircle the entire image ... like so:
<img width="406" alt="image" src="https://user-images.githubusercontent.com/2362647/151015371-cffbfb07-7a36-4784-b753-b9176387a872.png">

I'll play around with the image a little bit to see if I can get a proper ring around it without it looking too funky.
