### ISSUE TITLE
Weird frames requiring mask usage w/ tokenizer

### ISSUE THREAD

**Issue by abcdeed7** [jcolson/token_frames#6]
A fair few of the 'odd' token frames are requiring the mask to be used. a fair few of these it looks rather unpleasant. Notably this effects basically all the floral frames, and the Klingon frame (Seems that pngwing esp has issues?)

**Comment by jcolson** [comment]
thanks for the heads up. i had fixed several that were reported, didn't realize there were more.  i'll look at the floral and klingon first.
