### ISSUE TITLE
Tokens for Band of Blades

### ISSUE THREAD

**Issue by gus-uktena** [jcolson/token_frames#8]
Hello, I've just made some tokens for Band of Blades, which I would like to share with everyone. It includes a blank token so people can create their own variations. Thanks!

[Band_of_Blades_frames.zip](https://github.com/jcolson/token_frames/files/9072259/Band_of_Blades_frames.zip)
!

**Comment by jcolson** [comment]
you bet, I'll get them added in and released!  Thanks for sharing!
